"""followers

Revision ID: 648f744acd20
Revises: 5364c86f1f59
Create Date: 2022-05-14 17:46:07.354824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648f744acd20'
down_revision = '5364c86f1f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Followers')
    # ### end Alembic commands ###
